version: '3.9'
services:
  jenkins:
    build: .
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    environment: 
      - JENKINS_USER=root
      - JENKINS_PASS=root
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    container_name: jenkins
    volumes:
      - /home/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock